# Creating of Numpy Array


In [3]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series


In [14]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
list_4 = [14,15,16,17,18]
list_3 = [list_1,list_2,list_4]
my_array = np.array(list_3)
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [14, 15, 16, 17, 18]])

In [15]:
my_array.shape

(3, 5)

In [17]:
my_array.dtype

dtype('int64')

In [24]:
np.zeros((4,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.empty(4)

array([1., 1., 1., 1.])

In [42]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [44]:
my_array2=np.array([[2,3,4],[4,5,6]])
my_array2

array([[2, 3, 4],
       [4, 5, 6]])

In [49]:
my_array /5

array([[0.2, 0.4, 0.6, 0.8, 1. ],
       [1.2, 1.4, 1.6, 1.8, 2. ],
       [2.8, 3. , 3.2, 3.4, 3.6]])

In [63]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[5]

5

In [73]:
arr[3:]= 40
arr

array([ 0,  1,  2, 40, 40, 40, 40, 40, 40, 40, 40])

In [76]:
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
array3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
array3[:2][1]

array([5, 6, 7, 8])

In [101]:
arr2 = np.arange(40).reshape((5,8))
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [103]:
arr2.T

array([[ 0,  8, 16, 24, 32],
       [ 1,  9, 17, 25, 33],
       [ 2, 10, 18, 26, 34],
       [ 3, 11, 19, 27, 35],
       [ 4, 12, 20, 28, 36],
       [ 5, 13, 21, 29, 37],
       [ 6, 14, 22, 30, 38],
       [ 7, 15, 23, 31, 39]])

# Array preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [5]:
point = np.arange(-5, 5, 0.01)
point

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [8]:
dy = np.meshgrid(point,point)
dy

[array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]]),
 array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
        [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
        [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
        ...,
        [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
        [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
        [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])]